reviewers:
  defaults:
    - ritokuna
    - alkuma-san
    - yskoka

files:
  "tutorials/**":
    - ritokuna
    - alkuma-san
    - yskoka
  "_pages/**":
    - ritokuna
    - alkuma-san
    - yskoka
  ".github/**":
    - ritokuna
    - alkuma-san
    - yskoka

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 1
